version: '3.1'
services:
  web:
    image: koalasystems.azurecr.io/odoo-ca:${IMAGE_VERSION}
    depends_on:
      - db
    ports:
      - "${HOST_PORT}:8069"
      - "${LONGPOLLING_PORT}:8072"
    volumes:
      - type: bind
        source: ${DATA_PATH}/${DATABASE_NAME}/odoo
        target: /var/data/odoo
      - ./conf:/etc/odoo
    environment:
      HOST: db
      PORT: 5432
      USER: ${ODOO_DB_USER}
      PASSWORD_FILE: /run/secrets/postgresql_password
      DATABASE_NAME: ${DATABASE_NAME}
      ODOO_INITIAL_MODULES: ${ODOO_INITIAL_MODULES}
    secrets:
      - postgresql_password
    extra_hosts:
      - "odoo-host:host-gateway"
  db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
      POSTGRES_USER: ${ODOO_DB_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: ${DATA_PATH}/${DATABASE_NAME}/pgdata
        target: /var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password

secrets:
  postgresql_password:
    file: ./secrets/odoo_pg_pass